import { useState } from "react";
import { Link } from "react-router-dom";
import { fetchScriptHooks } from "../lib/api";
import type { Opportunity, ResearchLanguage, ResearchMarket } from "../lib/intelligence";
import { saveOpportunity } from "../lib/workspace";

interface Props { opportunities: Opportunity[]; seed: string; language: ResearchLanguage; market: ResearchMarket; token?: string | null; onAuthRequired: () => void; }

export default function OpportunityPanel({ opportunities, seed, language, market, token, onAuthRequired }: Props) {
  const [expanded,setExpanded]=useState<string|null>(null); const [hooks,setHooks]=useState<Record<string,string>>({}); const [loadingPhrase,setLoadingPhrase]=useState<string|null>(null); const [savingPhrase,setSavingPhrase]=useState<string|null>(null); const [saved,setSaved]=useState<Record<string,boolean>>({}); const [saveError,setSaveError]=useState<string|null>(null);
  async function generateHook(phrase:string){setLoadingPhrase(phrase);try{const result=await fetchScriptHooks(phrase,token);setHooks(c=>({...c,[phrase]:result}));setExpanded(phrase)}catch(error:any){setHooks(c=>({...c,[phrase]:error.message}));setExpanded(phrase)}finally{setLoadingPhrase(null)}}
  async function handleSave(item:Opportunity){if(!token){onAuthRequired();return}setSavingPhrase(item.phrase);setSaveError(null);try{await saveOpportunity({token,seed,opportunity:item,language,market});setSaved(c=>({...c,[item.phrase]:true}))}catch(error:any){setSaveError(error?.message||"Could not save opportunity")}finally{setSavingPhrase(null)}}
  if(!opportunities.length)return null;
  return <section className="opportunity-panel" aria-labelledby="opportunity-heading"><div className="opportunity-panel-heading"><div><span className="result-kicker">ASKLOOM OPPORTUNITY ENGINE · BETA</span><h3 id="opportunity-heading">Best opportunities in this research</h3></div><p>Scores currently use query structure, intent, specificity and first-party AskLoom momentum. They do not yet claim search volume or competition data.</p></div>{saveError&&<p className="opportunity-save-error" role="alert">{saveError}</p>}<div className="opportunity-list">{opportunities.slice(0,8).map((item,index)=><article className="opportunity-card" key={item.phrase}><div className="opportunity-rank">#{index+1}</div><div className="opportunity-score" aria-label={`Opportunity score ${item.score} out of 100`}><strong>{item.score}</strong><span>/100</span></div><div className="opportunity-content"><h4>{item.phrase}</h4><div className="opportunity-badges"><span>{item.intent.replace("-"," ")}</span>{item.badges.map(b=><span key={b}>{b}</span>)}</div>{expanded===item.phrase&&<div className="opportunity-details"><div><strong>Why it ranked</strong><ul>{item.reasons.map(r=><li key={r}>{r}</li>)}</ul></div>{hooks[item.phrase]&&<pre>{hooks[item.phrase]}</pre>}</div>}</div><div className="opportunity-actions"><button type="button" className="secondary-action" onClick={()=>setExpanded(expanded===item.phrase?null:item.phrase)}>{expanded===item.phrase?"Hide":"Why?"}</button><button type="button" className="secondary-action" disabled={savingPhrase===item.phrase||saved[item.phrase]} onClick={()=>handleSave(item)}>{saved[item.phrase]?"Saved":savingPhrase===item.phrase?"Saving...":"Save"}</button><button type="button" className="hook-btn opportunity-hook" disabled={loadingPhrase===item.phrase} onClick={()=>generateHook(item.phrase)}>{loadingPhrase===item.phrase?"Creating...":"Create hook"}</button><Link className="secondary-action" to={`/ai-studio?topic=${encodeURIComponent(item.phrase)}`}>AI Studio</Link></div></article>)}</div></section>;
}
