import * as React from "react"
import { addPropertyControls, ControlType } from "framer"

type Card={score:number;title:string;intent:string;source:string;reason:string}
const cards:Card[]=[
 {score:94,title:"How can small businesses use AI agents for customer service?",intent:"Question intent",source:"Google + YouTube",reason:"Specific, actionable and observed across both autocomplete sources."},
 {score:89,title:"AI agents vs virtual assistants for small business",intent:"Comparison intent",source:"Cross-source",reason:"Evaluation-style query with strong specificity and source convergence."},
 {score:84,title:"Best AI customer service tools for small business",intent:"Commercial intent",source:"Google source",reason:"Contains clear evaluation language and a specific use case."},
]
export default function OpportunityShowcase(props:any){const {title,subtitle}=props;return <div style={{width:"100%",fontFamily:"Inter,sans-serif",color:"#191C2B"}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"end",gap:20,marginBottom:22}}><div><div style={{fontSize:11,fontWeight:800,letterSpacing:".12em",color:"#765BDA"}}>OPPORTUNITY ENGINE</div><div style={{fontSize:34,fontWeight:700,letterSpacing:"-.045em",marginTop:7}}>{title}</div></div><div style={{maxWidth:430,fontSize:13,lineHeight:1.6,color:"#6C6E7B"}}>{subtitle}</div></div><div style={{display:"grid",gap:12}}>{cards.map((c,i)=><div key={c.title} style={{display:"grid",gridTemplateColumns:"56px 74px 1fr auto",gap:14,alignItems:"center",padding:"16px 18px",border:"1px solid #E7E1D5",borderRadius:18,background:"linear-gradient(180deg,#FFFDF8,#FAF5EA)",boxShadow:"0 10px 30px rgba(36,27,10,.04)"}}><div style={{fontSize:11,color:"#AAA29A",fontWeight:800}}>#{i+1}</div><div style={{height:54,borderRadius:14,border:"1px solid #D8C883",display:"grid",placeItems:"center",fontWeight:800,color:"#6D5707",background:"#FFF8D9"}}>{c.score}<span style={{fontSize:9,color:"#9B916F",marginTop:-14}}>/100</span></div><div><div style={{fontSize:15,fontWeight:730,lineHeight:1.35}}>{c.title}</div><div style={{display:"flex",gap:7,flexWrap:"wrap",marginTop:8}}><span style={badge}>{c.intent}</span><span style={badge}>{c.source}</span></div><div style={{fontSize:11,color:"#797A84",marginTop:8,lineHeight:1.5}}>{c.reason}</div></div><div style={{fontSize:18,color:"#765BDA"}}>↗</div></div>)}</div><div style={{marginTop:14,fontSize:11,color:"#8E8F99"}}>AskLoom does not claim search volume or competition data unless explicitly sourced. Scores remain methodology-led and auditable.</div></div>}
const badge:React.CSSProperties={fontSize:10,fontWeight:700,color:"#625E72",padding:"5px 8px",borderRadius:999,border:"1px solid #E3DDD1",background:"#F5F0E8"}
OpportunityShowcase.defaultProps={title:"Know what deserves your attention first.",subtitle:"AskLoom ranks discovered questions using intent, specificity, real autocomplete source evidence, first-party momentum and—only when statistically safe—historical outcome calibration."}
addPropertyControls(OpportunityShowcase,{title:{type:ControlType.String,title:"Title"},subtitle:{type:ControlType.String,title:"Subtitle",displayTextArea:true}})
