import { getAuthHeader } from "./auth";
import type { Opportunity, ResearchLanguage, ResearchMarket } from "./intelligence";
const API_BASE = import.meta.env.VITE_API_BASE || "http://localhost:4000/api";
export type ContentStatus = "IDEA" | "PLANNED" | "IN_PROGRESS" | "PUBLISHED";
export type EditorialDetails = { platform?: string | null; assignee?: string | null; dueDate?: string | null; selectedTitle?: string | null; publishedUrl?: string | null; publishedAt?: string | null; views?: number | null; engagements?: number | null; conversions?: number | null };
async function parse(res: Response, fallback: string) { if (!res.ok) { const err=await res.json().catch(()=>({})); throw new Error(err.error||fallback); } return res.json(); }
export async function saveOpportunity(input:{token:string;seed:string;opportunity:Opportunity;language:ResearchLanguage;market:ResearchMarket;projectId?:string|null}){return parse(await fetch(`${API_BASE}/account/opportunities`,{method:"POST",credentials:"include",headers:{"Content-Type":"application/json",...getAuthHeader(input.token)},body:JSON.stringify({projectId:input.projectId??null,seed:input.seed,phrase:input.opportunity.phrase,score:input.opportunity.score,intent:input.opportunity.intent,category:input.opportunity.category,language:input.language,market:input.market,reasons:input.opportunity.reasons})}),"Could not save opportunity")}
export async function fetchSavedOpportunities(token:string){return parse(await fetch(`${API_BASE}/account/opportunities`,{credentials:"include",headers:{...getAuthHeader(token)}}),"Could not load saved opportunities")}
export async function deleteSavedOpportunity(token:string,id:string){return parse(await fetch(`${API_BASE}/account/opportunities/${id}`,{method:"DELETE",credentials:"include",headers:{...getAuthHeader(token)}}),"Could not delete saved opportunity")}
export async function assignOpportunityToProject(token:string,id:string,projectId:string|null){return parse(await fetch(`${API_BASE}/account/opportunities/${id}/project`,{method:"PATCH",credentials:"include",headers:{"Content-Type":"application/json",...getAuthHeader(token)},body:JSON.stringify({projectId})}),"Could not move opportunity")}
export async function updateOpportunityStatus(token:string,id:string,contentStatus:ContentStatus){return parse(await fetch(`${API_BASE}/account/opportunities/${id}/status`,{method:"PATCH",credentials:"include",headers:{"Content-Type":"application/json",...getAuthHeader(token)},body:JSON.stringify({contentStatus})}),"Could not update content status")}
export async function updateEditorialDetails(token:string,id:string,details:EditorialDetails){return parse(await fetch(`${API_BASE}/account/opportunities/${id}/editorial`,{method:"PATCH",credentials:"include",headers:{"Content-Type":"application/json",...getAuthHeader(token)},body:JSON.stringify(details)}),"Could not update editorial details")}
export async function fetchProjects(token:string){return parse(await fetch(`${API_BASE}/account/projects`,{credentials:"include",headers:{...getAuthHeader(token)}}),"Could not load projects")}
export async function createProject(token:string,name:string,language:ResearchLanguage,market:ResearchMarket){return parse(await fetch(`${API_BASE}/account/projects`,{method:"POST",credentials:"include",headers:{"Content-Type":"application/json",...getAuthHeader(token)},body:JSON.stringify({name,language,market})}),"Could not create project")}
export async function deleteProject(token:string,id:string){return parse(await fetch(`${API_BASE}/account/projects/${id}`,{method:"DELETE",credentials:"include",headers:{...getAuthHeader(token)}}),"Could not delete project")}
